language: php

php:
  - 7.1

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover